// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proje05_MVC_EfCore_CodeFirst.Models;

#nullable disable

namespace Proje05_MVC_EfCore_CodeFirst.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221116135418_InitalDb")]
    partial class InitalDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Phones",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Computers",
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Electronics",
                            Name = "Electronic"
                        });
                });

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ankara"
                        });
                });

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Desc = "Güzel bir telefon",
                            Name = "IPhone13",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Desc = "Güzel bir bilgisayar",
                            Name = "Dell",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Desc = "Güzel bir sarj",
                            Name = "Powerbank",
                            Price = 5990m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Desc = "Güzel bir telefon",
                            Name = "IPhone14",
                            Price = 35000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
